import Image from "next/image"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowUpRight } from "lucide-react"
import { solutionDetails, solutionImages } from "@/data/site"

export function generateStaticParams(){return Object.keys(solutionDetails).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=solutionDetails[slug];return s?{title:s.title,description:s.description}:{}}
export default async function SolutionPage({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const solution=solutionDetails[slug];if(!solution)notFound()
  return <main><section className="relative isolate min-h-[720px] overflow-hidden bg-ink text-white"><Image src={solutionImages[slug]} alt="" fill priority sizes="100vw" className="-z-10 object-cover opacity-45" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-ink via-ink/90 to-ink/20" /><div className="technical-grid absolute inset-0 -z-10 opacity-20" /><div className="mx-auto grid min-h-[720px] max-w-7xl items-end gap-12 px-5 pb-24 pt-40 lg:grid-cols-[1fr_280px] lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-accent">{solution.eyebrow}</p><h1 className="mt-6 max-w-4xl font-display text-5xl font-bold leading-[.95] tracking-tight sm:text-7xl">{solution.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">{solution.description}</p><Link href="/rfq" className="button-primary mt-9">Send an RFQ <ArrowUpRight className="size-4" /></Link></div><div className="hidden border-l border-white/25 pl-6 lg:block"><p className="font-mono text-xs text-accent">{solution.eyebrow.split("/")[0]}</p><div className="mt-8 h-24 w-px bg-gradient-to-b from-accent to-transparent" /></div></div></section><section className="bg-paper text-ink"><div className="mx-auto grid max-w-7xl gap-px px-5 py-20 sm:grid-cols-2 lg:grid-cols-3 lg:px-8">{solution.items.map((item,index)=><div className="group border-l border-[#cad4d5] px-6 py-8" key={item}><span className="font-mono text-sm text-steel">0{index+1}</span><p className="mt-12 font-display text-xl font-semibold transition-transform group-hover:translate-x-2">{item}</p></div>)}</div></section><section className="bg-ink"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="max-w-xl border-l-2 border-accent pl-5 text-sm leading-7 text-white/60">Capabilities, product availability, specialist resources and delivery schedules are confirmed against individual enquiries and agreed scope.</p></div></section></main>
}
