import Image from "next/image"
import Link from "next/link"
import { ArrowDownRight, ArrowUpRight, Check, MoveUpRight } from "lucide-react"
import { capabilities, company, solutionImages } from "@/data/site"
import { ProcurementJourney } from "./procurement-journey"
import { IndustryExplorer } from "./industry-explorer"
import { Reveal } from "./reveal"

const notes = ["Specification-led sourcing for industrial and energy-sector requirements.", "Field-informed coordination for oilfield operations and interfaces.", "Mechanical, electrical and maintenance-related products and consumables.", "Appropriate third-party equipment and specialist resources against defined requirements.", "Electrical, measurement, monitoring and industrial control requirements.", "PPE, safety products and site consumables coordinated against the worksite need."]

export function Homepage() { return <main>
  <section className="relative isolate flex min-h-[min(920px,100svh)] items-end overflow-hidden bg-ink text-white">
    <div className="image-reveal absolute inset-0"><Image src="/industrial-hero.png" alt="Industrial energy infrastructure at blue hour" fill priority sizes="100vw" className="object-cover opacity-65" /></div><div className="absolute inset-0 bg-[linear-gradient(90deg,#071522_0%,rgba(7,21,34,.9)_38%,rgba(7,21,34,.18)_100%)]" /><div className="absolute inset-0 bg-[linear-gradient(0deg,#071522_2%,transparent_60%)]" /><div className="technical-grid absolute inset-0 opacity-30" />
    <div className="relative z-10 mx-auto grid w-full max-w-7xl gap-10 px-5 pb-16 pt-36 lg:grid-cols-[minmax(0,1fr)_260px] lg:px-8 lg:pb-24"><div><div className="eyebrow-light"><span className="technical-line h-px w-12 bg-accent" /> Energy &amp; Industrial Solutions</div><h1 className="mt-8 font-display text-[clamp(3.2rem,8vw,8.5rem)] font-bold leading-[.86] tracking-[-.055em]"><span className="headline-mask"><span>Technical</span></span><span className="headline-mask text-accent"><span>requirements.</span></span><span className="headline-mask"><span>Reliable sourcing.</span></span><span className="headline-mask"><span>Accountable delivery.</span></span></h1><p className="mt-9 max-w-xl text-base leading-7 text-white/70 sm:text-lg">Vertex supports energy and industrial organisations with specification-led procurement, industrial supply, oilfield support and specialist-service coordination.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/rfq" className="button-primary">Send an RFQ <ArrowUpRight className="size-4" /></Link><Link href="/solutions" className="button-line-light">Explore capabilities <ArrowDownRight className="size-4" /></Link></div></div><aside className="hidden self-end border-l border-white/30 pl-6 lg:block"><p className="font-mono text-xs text-accent">SPEC / SOURCE / SUPPLY</p><p className="mt-5 text-xs uppercase leading-6 tracking-[.2em] text-white/55">Pakistan<br />Technical procurement<br />Field support</p><div className="mt-10 h-20 w-px bg-gradient-to-b from-accent to-transparent" /><p className="mt-3 text-xs text-white/45">Scroll to trace<br />the requirement</p></aside></div>
  </section>
  <section className="overflow-hidden bg-paper text-ink"><div className="mx-auto max-w-7xl px-5 py-24 sm:py-36 lg:px-8"><Reveal><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow-dark"><span className="h-px w-12 bg-accent" /> The Vertex premise</p><p className="mt-8 max-w-xs text-sm leading-6 text-muted-ink">A requirement is more than a line item. It carries operating context, technical risk, documentation and a delivery consequence.</p></div><h2 className="font-display text-[clamp(3rem,7vw,7rem)] font-bold leading-[.88] tracking-[-.055em]">We don&apos;t start<br />with a catalogue.<br /><span className="text-steel">We start with<br />the requirement.</span></h2></div></Reveal><div className="technical-line mt-20 border-t border-[#cad4d5] pt-5 text-[10px] font-bold uppercase tracking-[.2em] text-muted-ink">Understand / Define / Source / Coordinate / Deliver</div></div></section>
  <section className="bg-ink text-white"><div className="mx-auto max-w-7xl px-5 py-24 sm:py-32 lg:px-8"><Reveal><p className="eyebrow-light"><span className="h-px w-12 bg-accent" /> Core capabilities</p><h2 className="mt-7 font-display text-5xl font-bold leading-[.9] sm:text-7xl">Built around the<br /><span className="text-accent">operational need.</span></h2></Reveal><div className="mt-16 grid gap-px bg-white/15 lg:grid-cols-2">{capabilities.map(([number,title,,href],index) => { const slug=href.split("/").pop()!; return <Link href={href} key={href} className={`group relative min-h-64 overflow-hidden bg-ink p-7 sm:p-9 ${index===0?"lg:row-span-2 lg:min-h-[520px]":""}`}><Image src={solutionImages[slug]} alt="" fill sizes="(min-width:1024px) 50vw,100vw" className="object-cover opacity-25 transition duration-700 group-hover:scale-105 group-hover:opacity-45" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/40 to-transparent" /><div className="relative flex justify-between"><span className="font-mono text-sm text-accent">{number}</span><MoveUpRight className="size-5 text-white/40" /></div><div className="absolute inset-x-7 bottom-8"><h3 className={`${index===0?"text-4xl sm:text-6xl":"text-2xl sm:text-3xl"} font-display font-semibold leading-[.95]`}>{title}</h3><p className="mt-5 max-w-sm text-sm leading-6 text-white/65">{notes[index]}</p></div><span className="absolute bottom-0 left-0 h-1 w-0 bg-accent transition-all duration-500 group-hover:w-full" /></Link>})}</div></div></section>
  <section className="bg-paper text-ink"><div className="mx-auto max-w-7xl px-5 py-24 sm:py-32 lg:px-8"><Reveal><p className="eyebrow-dark"><span className="h-px w-12 bg-steel" /> Signature experience</p><h2 className="mt-7 font-display text-5xl font-bold leading-[.9] sm:text-7xl">From specification<br /><span className="text-steel">to supply.</span></h2><p className="mt-7 max-w-xl text-base leading-7 text-muted-ink">A disciplined path from the first enquiry to a documented handover. Select a stage to see what the requirement needs next.</p></Reveal><ProcurementJourney /></div></section>
  <section className="relative overflow-hidden bg-steel text-white"><div className="absolute inset-y-0 right-0 w-full lg:w-1/2"><Image src="/oil-gas-field.png" alt="Oil and gas field environment" fill sizes="(min-width:1024px) 50vw,100vw" className="object-cover opacity-45 mix-blend-luminosity" /><div className="absolute inset-0 bg-gradient-to-r from-steel via-steel/70 to-transparent" /></div><Reveal className="relative mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:py-32 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow-light"><span className="h-px w-12 bg-accent" /> Field-informed support</p><h2 className="mt-7 font-display text-5xl font-bold leading-[.9] sm:text-7xl">The field context<br /><span className="text-accent">behind the process.</span></h2><p className="mt-7 max-w-md leading-7 text-white/70">Specification accuracy, equipment readiness, logistics, documentation and coordination directly affect operational continuity.</p><Link href="/leadership/babar-ali-malik" className="button-line-light mt-9">View professional background <ArrowUpRight className="size-4" /></Link></div></Reveal></section>
  <section className="bg-paper text-ink"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><Reveal><p className="eyebrow-dark"><span className="h-px w-12 bg-accent" /> Working environments</p><h2 className="mt-7 font-display text-4xl font-bold leading-[.92] sm:text-6xl">Different sectors.<br /><span className="text-steel">Same discipline.</span></h2></Reveal><IndustryExplorer compact /></div></section>
  <section className="bg-ink text-white"><div className="mx-auto flex max-w-7xl flex-col gap-10 px-5 py-24 sm:py-32 lg:flex-row lg:items-end lg:justify-between lg:px-8"><div><p className="eyebrow-light"><span className="h-px w-12 bg-accent" /> Start an enquiry</p><h2 className="mt-7 font-display text-5xl font-bold leading-[.88] sm:text-8xl">Have a technical<br /><span className="text-accent">requirement?</span></h2></div><div className="flex flex-col items-start gap-5"><Link href="/rfq" className="button-primary">Send an RFQ <ArrowUpRight className="size-4" /></Link><a href={company.whatsappHref} className="button-line-light">WhatsApp Vertex <Check className="size-4" /></a></div></div></section>
</main> }
