"use client"
import { useEffect, useRef, useState } from "react"
import { ArrowRight, Check } from "lucide-react"

const stages = [["01","Requirement","RFQ, BOQ, drawing, datasheet, part number or operating problem."],["02","Technical review","Application, service conditions, location, quantity and acceptance criteria."],["03","Specification","A clear scope with documentation, responsibilities, schedule and exclusions."],["04","Sourcing","Suitable suppliers, products, specialists, availability and alternatives."],["05","Commercial offer","Transparent brand, model, lead time, warranty and documentation details."],["06","Coordination","Procurement, logistics, site needs and specialist interfaces aligned."],["07","Delivery","The accepted scope checked against the requirement and discrepancies identified."],["08","Handover","Agreed delivery notes, service records, certificates and follow-up information."]] as const

export function ProcurementJourney() {
  const [active,setActive]=useState(0); const refs=useRef<(HTMLLIElement|null)[]>([]); const current=stages[active]
  useEffect(()=>{ const observers=refs.current.map((node,index)=>{ if(!node)return null; const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)setActive(index)},{rootMargin:"-42% 0px -42%",threshold:0}); observer.observe(node); return observer }); return()=>observers.forEach(o=>o?.disconnect()) },[])
  return <div className="mt-14 grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-20">
    <div className="lg:sticky lg:top-32 lg:self-start"><div className="flex justify-between text-[10px] font-bold uppercase tracking-[.2em] text-steel"><span>Vertex procurement track</span><span>{current[0]} / 08</span></div><div className="mt-6 h-px bg-[#cad4d5]"><div className="h-px bg-steel transition-all duration-700" style={{width:`${(active+1)*12.5}%`}} /></div><div key={active} className="stage-detail mt-12 min-h-64"><p className="font-mono text-6xl font-bold text-[#b7c4c5]">{current[0]}</p><h3 className="mt-4 font-display text-4xl font-bold sm:text-5xl">{current[1]}</h3><p className="mt-5 max-w-sm leading-7 text-muted-ink">{current[2]}</p></div><div className="flex items-center gap-3 text-sm font-semibold"><Check className="size-4 text-steel" />Scope stays visible at every stage.</div></div>
    <ol className="grid gap-0">{stages.map(([number,title,description],index)=><li ref={node=>{refs.current[index]=node}} className="min-h-[42vh] lg:min-h-[55vh]" key={number}><button type="button" onClick={()=>setActive(index)} className={`group grid w-full grid-cols-[48px_1fr_auto] items-center gap-4 border-b border-[#cad4d5] py-6 text-left transition ${active===index?"text-ink":"text-muted-ink"}`} aria-current={active===index?"step":undefined}><span className="font-mono text-sm text-steel">{number}</span><span><span className="block font-display text-xl font-semibold sm:text-2xl">{title}</span><span className="mt-2 block text-sm leading-6 lg:hidden">{description}</span></span><ArrowRight className={`size-5 transition-transform ${active===index?"translate-x-1 text-accent":"text-[#9aa9aa]"}`} /></button></li>)}</ol>
  </div>
}
